# Site settings
title: taniken's portfolio
email: kento.tani@seattleconsulting.co.jp
url: https://tanikento.github.io
description: "Web Engineer"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#FF0000'

# Footer settings
footer: taniken's portfolio

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/tanikenbz
  - title: github
    url: https://github.com/tanikento

# Build settings
markdown: kramdown
permalink: pretty
